//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPrajwalService")]
    public interface IPrajwalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrajwalService/GetData", ReplyAction="http://tempuri.org/IPrajwalService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrajwalService/GetData", ReplyAction="http://tempuri.org/IPrajwalService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrajwalService/Insert", ReplyAction="http://tempuri.org/IPrajwalService/InsertResponse")]
        int Insert(WcfService3.GenderTable GenderPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrajwalService/Insert", ReplyAction="http://tempuri.org/IPrajwalService/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(WcfService3.GenderTable GenderPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrajwalService/View", ReplyAction="http://tempuri.org/IPrajwalService/ViewResponse")]
        System.Collections.Generic.Dictionary<string, string> View(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrajwalService/View", ReplyAction="http://tempuri.org/IPrajwalService/ViewResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> ViewAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrajwalServiceChannel : WpfApp3.ServiceReference1.IPrajwalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrajwalServiceClient : System.ServiceModel.ClientBase<WpfApp3.ServiceReference1.IPrajwalService>, WpfApp3.ServiceReference1.IPrajwalService {
        
        public PrajwalServiceClient() {
        }
        
        public PrajwalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrajwalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrajwalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrajwalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int Insert(WcfService3.GenderTable GenderPar) {
            return base.Channel.Insert(GenderPar);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(WcfService3.GenderTable GenderPar) {
            return base.Channel.InsertAsync(GenderPar);
        }
        
        public System.Collections.Generic.Dictionary<string, string> View(int Id) {
            return base.Channel.View(Id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> ViewAsync(int Id) {
            return base.Channel.ViewAsync(Id);
        }
    }
}
